/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kr.disdong.diff.checker

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class DiffCheckerPluginTest {
    @Test
    fun `plugin registers task`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("kr.disdong.diff.checker")

        project.extensions.configure(Input::class.java) {
            it.baseDir.set("/bin/bash")
            it.targetDir.set("**/http/response")
            it.targetFile.set("**/*.json")
        }

        assertNotNull(project.tasks.findByName("diffChecker"))
        assertEquals(project.extensions.getByType(Input::class.java).baseDir.get(), "/bin/bash")
        assertEquals(project.extensions.getByType(Input::class.java).targetDir.get(), "**/http/response")
        assertEquals(project.extensions.getByType(Input::class.java).targetFile.get(), "**/*.json")
    }
}
