/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kr.disdong.diff.checker

import kr.disdong.diff.checker.core.DiffChecker
import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.provider.Property


// https://peachytree.tistory.com/m/4
interface Input {
    val baseDir: Property<String>
    val targetDir: Property<String>
    val targetFile: Property<String>
}


class DiffCheckerPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val input = project.extensions.create("diffChecker", Input::class.java)

        // Register a task
        project.tasks.register("diffChecker") { task ->
            val checker = DiffChecker(
                input.baseDir.get(),
                input.targetDir.getOrElse("**/http/response"),
                input.targetFile.getOrElse("**/*.json"),
            )

            task.doLast {
                checker.run()
            }
        }
    }
}
