/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kr.disdong.plugin.template

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class PluginTemplate: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("pluginTemplate") { task ->
            task.doLast {
                println("Hello from plugin 'kr.disdong.plugin.template'")
            }
        }
    }
}
