/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kr.disdong.plugin.template

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'diff.checker.greeting' plugin.
 */
class PluginTemplateTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("kr.disdong.plugin.template")

        // Verify the result
        assertNotNull(project.tasks.findByName("pluginTemplate"))
    }
}
